server:
  port: 8000

eureka:
  instance:
    lease-renewal-interval-in-seconds: 1 #heartbeat interval
    lease-expiration-duration-in-seconds: 2 # waiting 2 second before undo
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway
#  cloud:
#    gateway:
#      routes:
#        - id: #application name
#          uri: #entry address
#          predicates: #condition

